coral-component-calendar/i18n/translations.js
coral-component-calendar/src/templates/calendar.html

buttons change months should have specific labels
CUI-7337

CUI-7337 buttons change months should have specific labels

---

coral-externals/index.js
package-lock.json
package.json

A review of the code indicates that no other parts are affected by the breaking changes in the library update.
I have run all the testcases locally and they all succeed.

Updated core-js to version 3

---

coral-component-table/src/scripts/Table.js
coral-component-table/src/tests/snippets/Table.tfoot.html
coral-component-table/src/tests/test.Table.js

Prevent double voicing of `thead` items with redundant `tfoot`
With a thead and tfoot, if the number of rows in the thead and tfoot match, and the textContent of each thead header cell matches the textContent of each tfoot header cell in the same column, the tfoot is redundant and should be hidden to prevent double or triple voicing of table headers.
Evaluate against example at: http://127.0.0.1:9001/examples/#table with heading "Sortable + orderable columns" and the following markup
```html
<table is="coral-table">
<colgroup>
<col is="coral-table-column" orderable="" sortable="" sortabledirection="ascending">
<col is="coral-table-column" orderable="" sortable="" sortabletype="number">
<col is="coral-table-column" sortable="" sortabletype="date">
</colgroup>
<thead is="coral-table-head"> …
```

[Accessibility] Table: prevent double voicing of thead items with redundant tfoot

---

dist/examples/index.html

Ability to search for components (in examples) via any parts of the text, not just beginning of it.

Ability to search for components (in examples) via any parts of the text, not just beginning of it.

---

README.md

Update "Using Coral Spectrum" section with better docs for distribution.

Update "Using Coral Spectrum" section with better docs for distribution.

---

README.md

I think it's important to emphasize those links. They are extremely valuable for development!

Update README.md to emphasize examples and API links

---

coral-component-actionbar/src/scripts/ActionBar.js
coral-component-actionbar/src/scripts/getFirstSelectableWrappedItem.js
coral-component-actionbar/src/templates/overlayContent.html
coral-component-actionbar/src/tests/snippets/ActionBar.hiddenitems.html
coral-component-actionbar/src/tests/test.ActionBar.js

CUI-7384 : [Coral-Actionbar] Actionbar improvements for accessibility.

---

coral-component-columnview/src/styles/dark.styl
coral-component-columnview/src/styles/darkest.styl
coral-component-columnview/src/styles/light.styl
coral-component-columnview/src/styles/lightest.styl
coral-component-columnview/src/styles/skin.styl

update copyright for new files from (#81)
This is a follow-up to code comments:
- https://github.com/adobe/coral-spectrum/commit/5fce566fbe6a7dc6c6575b6fd799b88900ff8d45#r39280339
- https://github.com/adobe/coral-spectrum/commit/5fce566fbe6a7dc6c6575b6fd799b88900ff8d45#r39280346
- https://github.com/adobe/coral-spectrum/commit/5fce566fbe6a7dc6c6575b6fd799b88900ff8d45#r39280349
- https://github.com/adobe/coral-spectrum/commit/5fce566fbe6a7dc6c6575b6fd799b88900ff8d45#r39280352

@trivial update copyright for new files from (#81)

---

coral-component-actionbar/src/scripts/ActionBarPrimary.js
coral-component-actionbar/src/scripts/ActionBarSecondary.js
coral-component-actionbar/src/scripts/BaseActionBarContainer.js
coral-component-actionbar/src/templates/overlayContent.html
coral-component-actionbar/src/tests/test.ActionBar.js

These changes fix the id duplication of popover when an action is moved to/from more popover.
https://github.com/adobe/coral-spectrum/issues/110
These changes fix the id duplication of popover when an action is moved to/from more popover.
Test Added.

issues#110 - Popovers with same id in Coral.Actionbar.

---

coral-component-shell/src/styles/solutionswitcher/index.styl

Add underline to hover and focus states.
https://jira.corp.adobe.com/browse/CQ-4282072
Provide better affordance on hover and focus for links in Shell Solution Switcher.
Tested in Shell example

CQ-4282072 Improve coral-component-shell-solutionswitcher focus and hover styles

---

.github/workflows/release.yml
.releaserc.js
README.md
package-lock.json
package.json

Add automatic semantic release

---

coral-css-decoratedtextfield/src/styles/index.styl

https://jira.corp.adobe.com/browse/CUI-7431

fix(CUI-7431) : Regression Close(clear) button of Search box is misaligned

---

coral-component-actionbar/src/scripts/ActionBarSecondary.js

fix: don't change buttons order in actionbar "More" popover

---

coral-component-button/src/styles/index.styl

Reverts adobe/coral-spectrum#169

Revert "CQ-4290733 : [Visual Requirements-AEM Dynamic Media-Image Set Editor]…"

---

coral-component-button/src/styles/index.styl

…ot meets minimum luminosity ratio 4.5:1 (#169)
* CQ-4290733 : [Visual Requirements-AEM Dynamic Media-Image Set Editor]: Luminosity ratio fails for multiple controls, does not meets minimum luminosity ratio 4.5:1.
* CQ-4290733 : [Visual Requirements-AEM Dynamic Media-Image Set Editor]: Luminosity ratio fails for multiple controls, does not meets minimum luminosity ratio 4.5:1.

fix(CQ-4290733): Luminosity ratio fails for multiple controls, does not meets minimum luminosity ratio 4.5:1 (#169)

---

coral-component-masonry/src/scripts/Masonry.js

Reverting a small change introduced in #170

fix: resizing masonry should perform layouting

---

coral-base-button/src/scripts/BaseButton.js
coral-base-component/src/scripts/BaseComponent.js
coral-base-fieldgroup/src/scripts/BaseFieldGroup.js
coral-base-formfield/src/scripts/BaseFormField.js
coral-base-list/src/scripts/BaseList.js
coral-base-list/src/scripts/BaseListItem.js
coral-base-overlay/src/scripts/BaseOverlay.js
coral-component-actionbar/src/scripts/ActionBar.js
coral-component-columnview/src/scripts/ColumnView.js
coral-component-columnview/src/scripts/ColumnViewColumn.js
coral-component-columnview/src/scripts/ColumnViewItem.js
coral-component-columnview/src/styles/index.styl
coral-component-icon/src/scripts/Icon.js
coral-utils/src/scripts/Commons.js

The columnview takes some time to load when number of items increases. As the number of items increases the time to load increase. 
We have tried to decrease the loading time for columview. Below are the changes are we introducing : 
a) Avoid the re-execution of code in case the property value already set.
b) Avoid memory leak in case the element is constructed but never added in DOM and weakmap in resize observer. The related change would be : https://github.com/adobe/coral-spectrum/pull/185/files#diff-e1ff43dbdd4c750dc77c24168dc5abbff2b7c89a1d0c9662fdb8100b2d916838R848 and https://github.com/adobe/coral-spectrum/pull/185/files#diff-878f0bc86b366d31023935e26fe2a5979cfd2c339121a36dbe3ee390472a0f87R112 
c) Avoid layout shift in case of columnview : …

fix: [Performance] Improvements in Columnview

---

coral-component-table/src/tests/test.Table.js

fix: Correcting failing testcase

---

coral-component-toast/src/scripts/Toast.js

…y announced
Jira Ticket:
https://jira.corp.adobe.com/browse/ASSETS-6815
Added aria-live to the toast component

fix(ASSETS-6815): Added aria-live to toast component to announce automatically

---

coral-component-shell/src/styles/header/index.styl

https://jira.corp.adobe.com/browse/SITES-2854

fix(SITES-2854): reduce the margin-right size of icon

---

coral-component-button/src/styles/index.styl
coral-component-select/src/styles/index.styl
coral-component-textfield/src/styles/index.styl
coral-theme-spectrum/src/styles/vars.css

fix(ASSETS-6851): The selected state of the action button does not have a sufficient contrast ratio

---

coral-gulp/configs/karma.conf.js

fix: Correcting failing build

---

coral-component-shell/src/styles/index.styl

https://jira.corp.adobe.com/browse/SITES-2855
With this fix, you can no longer scroll at 320px:
Before:
After:

Accessibility - Horizontal scrolling at 320px width.

---

coral-gulp/configs/karma.conf.js

fix: Run testcases on firefox

---

coral-component-shell/src/styles/user/index.styl

fix(ASSETS-17269): Text content lacks 4.5:1 contrast ratio

---

coral-component-taglist/src/scripts/Tag.js

fix(ASSETS-17256): Function cannot be performed by keyboard alone

---

coral-component-table/src/styles/light.styl
coral-component-table/src/styles/skin.styl
coral-theme-spectrum/src/styles/vars.css

https://jira.corp.adobe.com/browse/ASSETS-17260
raised contrast ratio

fix(ASSETS-17260): State of active component lacks 3 to 1 contrast ratio

---

coral-theme-spectrum/src/styles/vars.css

https://jira.corp.adobe.com/browse/SITES-10905
https://git.corp.adobe.com/Granite/com.adobe.granite.ui.coral-spectrum/pull/163
With this change, I fixed the contrast issue
Before:
After:

fix(accessibility): State of active component lacks 3 to 1 contrast ratio.

---

coral-component-accordion/src/scripts/AccordionItem.js

This fixes accessibility requirements by setting "tabindex=0" to the AccordionItem Buttons, AccordionItems are currently interactively using up/down keys once the focus is inside Accordion. As per Accessbility, the accordion items should be tabbable.
Bug fix - JIRA ticket [https://jira.corp.adobe.com/browse/FORMS-6762](url)
Fixes accessibility issues as specified in the JIRA.
Bugs filed as a result of an accessibility audit.
Manual testing.
Automated tests.

fix: Accordion Items tabbable.

---

coral-component-shell/src/styles/index.styl

https://jira.corp.adobe.com/browse/SITES-14128
With this change, I solved the issue mentioned in the ticket and the style was added according to SITES-2855. (https://jira.corp.adobe.com/browse/SITES-2855)
Before:
After:

fix(bug): Shell header menu is being cut off

---

coral-component-actionbar/src/scripts/ActionBarContainerCollection.js
coral-component-actionbar/src/scripts/getFirstSelectableWrappedItem.js

fix: ActionBar items moves focus to disabled items.

---

coral-component-tablist/src/styles/skin.styl

[SITES-13798](https://jira.corp.adobe.com/browse/SITES-13798)
added border with 1px solid

fix(Accessibility): focus is not visible when the high contrast mode is enabled.

---

coral-component-toast/src/scripts/Toast.js
coral-component-toast/src/tests/test.Toast.js

https://jira.corp.adobe.com/browse/ASSETS-25755
Updated to use role="alert" to enforce screen reader announcement.

fix: Update the role to alert for success toast

---

coral-component-shell/src/scripts/ShellHelpItem.js
coral-component-shell/src/templates/help.html

Added role list to coral-Shelp-items container and role listitem to its items.
https://jira.corp.adobe.com/browse/SITES-10929

fix: Coral shell help items should have list role

---

coral-component-shell/src/styles/header/index.styl
coral-theme-spectrum/src/styles/vars.css

https://jira.corp.adobe.com/browse/SITES-10935
With these color changes, I adjusted the contrast, which can be seen in the images below (the contrast must be at least 3:1)

fix: Correct anchor color and header text color

---

coral-component-colorinput/src/templates/swatchesHeader.html

Changed role of swatchers container from presentation to listbox.
https://jira.corp.adobe.com/browse/SITES-3055

fix: Ensure interactive controls are not nested.

---

coral-component-colorinput/src/scripts/ColorInput.js

JIRA Ticket: https://jira.corp.adobe.com/browse/SITES-11992

fix(Accessibility): Annotation swatch selector button missing an accessible name

---

coral-component-colorinput/src/scripts/ColorInput.js
package-lock.json

fix(bug): Custom color coral ui element is non-functional

---

coral-component-colorinput/src/styles/index.styl
coral-component-fileupload/src/scripts/FileUpload.js
coral-component-fileupload/src/tests/test.FileUpload.js

fix: correct axe violations

---

coral-component-dialog/src/tests/test.Dialog.js
coral-component-table/examples/index.html
coral-component-table/i18n/translations.js
coral-component-table/src/scripts/Table.js
coral-component-table/src/scripts/TableRow.js
coral-component-table/src/tests/test.Table.js
coral-dragaction/src/scripts/DragAction.js
coral-dragaction/src/tests/test.DragAction.js
coral-gulp/configs/karma.conf.js
coral-utils/src/scripts/Commons.js
coral-utils/src/scripts/Events.js

JIRA Ticket: https://jira.corp.adobe.com/browse/SITES-2864

fix (SITES-2864): Drag and Drop feature is not keyboard accessible

---

coral-component-fileupload/src/scripts/FileUpload.js

fix: correct NPE in fileupload

---

coral-component-clock/src/tests/test.Clock.js
coral-component-datepicker/src/tests/test.Datepicker.js
coral-component-overlay/src/scripts/Overlay.js
coral-component-popover/src/scripts/Popover.js
coral-component-select/src/scripts/Select.js
coral-component-select/src/scripts/SelectItem.js
coral-component-select/src/tests/test.Select.Item.js
coral-component-select/src/tests/test.Select.js
coral-messenger/src/scripts/Messenger.js
package-lock.json

The select item and multi field items when large in number result in too much page load time. With this changes we are expecting to improve the performance gain.

feat(perf): select item and multifield items are taking too much time

---

coral-collection/src/scripts/Collection.js
coral-collection/src/scripts/SelectableCollection.js
coral-component-list/src/scripts/SelectList.js
coral-component-tablist/src/scripts/TabList.js
package-lock.json

There was a performance dip when there are large number of coral select item exists in DOM. This change will enhance the performance.

feat(perf): Performance Issue with Coral Select Field

---

coral-component-steplist/src/scripts/StepList.js

Ticket: [SITES-26895](https://jira.corp.adobe.com/browse/SITES-26895)
made steps keyboard accessible when screen is set to small

fix(Accessibility): made steps keyboard accessible when screen is set to small

---

coral-component-dialog/src/scripts/Dialog.js

corrected aria-modal value
ticket: [SITES-26873](https://jira.corp.adobe.com/browse/SITES-26873)

fix(accessibility): Ensures all ARIA attributes have valid values

---

coral-component-select/src/scripts/Select.js

fix: dropdown selection values are not getting selected

---

coral-component-table/src/styles/skin.styl

Added underline style to match the 650 version
https://jira.corp.adobe.com/browse/SITES-26890

SITES-26890: Accessibility - While using Keyboard, Scope Table headers keyboard focus is not visible in Manage Publication

---

coral-component-popover/src/scripts/Popover.js

The placement of coral-select is not correct. This PR targets to correct the UI placement.

fix: Correct coral-select popover placement

---

coral-component-quickactions/src/scripts/QuickActions.js

Ticket [SITES-24938](https://jira.corp.adobe.com/browse/SITES-24938)
Added aria label for the quickactions wrapper

fix (Accessibility) SITES-24938 Card Actions Menu Bar does not have an accessible name

---

coral-component-numberinput/src/scripts/NumberInput.js

removed duplicated aria-labelledby from the input if the wrapper already have one
[SITES-24725](https://jira.corp.adobe.com/browse/SITES-24725)

fix: Spin button screen reader feedback is verbose

---

coral-base-overlay/src/scripts/BaseOverlay.js

JIRA Ticket: https://jira.corp.adobe.com/browse/SITES-24504
this PR is related to the PR here
https://git.corp.adobe.com/CQ/ui-wcm-editor/pull/1277

SITES-24504 Button does not communicate correct expanded / collapsed state

---

coral-component-dialog/src/scripts/Dialog.js

fix: added a new line
