examples/index.html
User should be able to navigate through SideNav items using the Tab key, and SideNav items should be identified a links using assistive technology.
SideNav items are skipped entirely. Using a screen reader the SideNav items are identified as static text.
Note: this commit includes a few other small accessibility fixes to:
1. Control visibility of sidenav when it is collapsed in responsive mode. A user should not be able to tab to items in a collapses side nav.
2. Use an actual button that communicates state for the navigation toggle button
3. Improve labelling of Search control
4. Improve labelling of Adobe logo
5. Add landmark regions
#6 / [CORAL-158](https://jira.corp.adobe.com/browse/CORAL-158)
Example documentation for Coral Spectrum components should be accessible.
These changes …
=> 🐛fix #6/CORAL-158 SideNav on Examples page is not keyboard accessible

coral-base-overlay/src/scripts/BaseOverlay.js
When the coral-base-overlay initializes, but the element called with the `returnFocusTo` method is not yet in the DOM, the element will receive `tabindex="-1"` even if it would be focusable following initialization and render.
This can be seen on: https://opensource.adobe.com/coral-spectrum/dist/examples/coral-component-select.html, where the Select buttons are not tabbable after the page loads.
See: https://git.corp.adobe.com/Coral/coralui-mixin-overlay/commit/6e14b827c6ff163e65f24ee526cae2d0bb09b555#r161631, where tabindex="-1" is added after evaluating element.parentNode === null and https://github.com/adobe/coral-spectrum/blob/master/coral-base-overlay/src/scripts/BaseOverlay.js#L896
Remove `element.parentNode === null` test in `BaseOverlay.returnFocusTo()` method. …
=> CUI-7340 [Accessibility] Coral.Select should be tabbable after initialization

coral-component-tree/examples/index.html, coral-component-tree/i18n/translations.json, coral-component-tree/src/scripts/Tree.js, coral-component-tree/src/scripts/TreeItem.js, coral-component-tree/src/styles/index.styl, coral-component-tree/src/templates/treeItem.html, coral-component-tree/src/tests/test.Tree.js
Per: https://jira.corp.adobe.com/browse/CQ-4272964
Fix the Coral-Spectrum Tree implementation to better conform with WAI-ARIA Authoring Practice design pattern: https://www.w3.org/TR/wai-aria-practices-1.2/#TreeView
#10 and https://jira.corp.adobe.com/browse/CUI-7339
Ensure accessibility of Tree with desktop and mobile screen readers/
1. Unit tests have been updated.
2. Manually tested using the following browser/screen reader combinations:
- macOS 10.15.2/VoiceOver/Safari 13.0.4 (15608.4.9.1.3)
- macOS 10.15.2/VoiceOver/Chrome 79.0.3945.88 (Official Build) (64-bit)
- iOS 13.2.3/VoiceOver/Safari
This PR changes the keyboard behavior to better conform with with WAI-ARIA Authoring Practice design pattern: https://www.w3.org/TR/wai-aria-practices-1.2/#TreeView, but the keyboard behavior is …
=> fix #10 [Accessibility] Coral.Tree fix WAI-ARIA implementation to improve screen reader support

coral-base-list/src/scripts/BaseListItem.js, coral-component-anchorbutton/src/scripts/AnchorButton.js, coral-component-anchorbutton/src/tests/test.AnchorButton.js, coral-component-autocomplete/src/scripts/Autocomplete.js, coral-component-buttongroup/src/scripts/ButtonGroup.js, coral-component-calendar/src/scripts/Calendar.js, coral-component-checkbox/src/scripts/Checkbox.js, coral-component-clock/src/scripts/Clock.js, coral-component-colorinput/src/scripts/ColorInput.js, coral-component-cyclebutton/src/scripts/CycleButtonItem.js, coral-component-datepicker/src/scripts/Datepicker.js, coral-component-drawer/src/scripts/Drawer.js, coral-component-list/src/scripts/SelectListItem.js, coral-component-numberinput/src/scripts/NumberInput.js, coral-component-numberinput/src/tests/test.NumberInput.js, coral-component-radio/src/scripts/Radio.js, coral-component-search/src/scripts/Search.js, coral-component-select/src/scripts/Select.js, coral-component-slider/src/scripts/Slider.js, coral-component-status/src/scripts/Status.js, coral-component-status/src/tests/test.Status.js, coral-component-switch/src/scripts/Switch.js, coral-component-tablist/src/scripts/Tab.js, coral-component-tablist/src/tests/test.Tab.js, coral-component-tablist/src/tests/test.TabList.js, coral-component-taglist/src/scripts/TagList.js, coral-component-tree/src/scripts/TreeItem.js, examples/compat/Coral.Element.js
When an element is not disabled, it does not require nor should it have the aria-disabled="false" property.
https://jira.corp.adobe.com/browse/CUI-7348 and #12 / https://jira.corp.adobe.com/browse/CUI-7343
Simplify rendering of elements when they are not disabled.
Tested in context of #12 / https://jira.corp.adobe.com/browse/CUI-7343
=> CUI-7348 [Accessibility] remove aria-disabled="false" when an element is not disabled

coral-base-overlay/src/scripts/BaseOverlay.js, coral-base-overlay/src/templates/base.html
In Coral Spectrum, the tabCapture elements created by BaseOverlay, and in CoralUI, the tabCapture elements created by coralui-mixin-overlay should have role=presentation, so that assistive technology does not count them as children in components, like role="menu" or role="listbox", where child count is relevant.
https://jira.corp.adobe.com/browse/CUI-7344 and 
Helps prevent assistive technology from announcing the wrong number of children in a menu or listbox.
Tested in relation to #12 and https://jira.corp.adobe.com/browse/CUI-7343
=> CUI-7344 [Accessibility] Overlay tabCapture elements should have role=presentation

coral-base-list/src/scripts/BaseList.js, coral-component-list/src/scripts/SelectList.js, coral-component-tablist/src/tests/test.TabList.js
In SelectList and ButtonList, keyboard event handlers for navigation with Arrow keys, PageUp/Down, Home or End should not call stopPropagation on the event.
In CycleButton, it is important for the CycleButton component to handle keyboard events from the SelectList and ButtonList in its Popover, so that the dropdown navigates as a single menu, rather than a dialog with two distinct tab stops that looks just like a menu.
https://jira.corp.adobe.com/browse/CUI-7346 and #12 / https://jira.corp.adobe.com/browse/CUI-7343
Tested in relation to #12 and https://jira.corp.adobe.com/browse/CUI-7343
=> CUI-7346 [Accessibility] Lists should not stopPropagation with keyboard navigation

coral-component-cyclebutton/examples/index.html, coral-component-cyclebutton/src/scripts/CycleButton.js, coral-component-cyclebutton/src/scripts/CycleButtonAction.js, coral-component-cyclebutton/src/scripts/CycleButtonItem.js, coral-component-cyclebutton/src/templates/base.html, coral-component-cyclebutton/src/tests/test.CycleButton.js
Per: https://jira.corp.adobe.com/browse/GRANITE-28179
Coral.CycleButton currently opens a dropdown containing a listbox of coral-cyclebutton-items, and a coral-buttonlist of coral-cyclebutton-actions, which makes interaction difficult for a keyboard or screen reader user, because it is not clear that the dropdown, that looks like a menu, contains more than one tab stop.
The dropdown should behave as a single menu with coral-cyclebutton-items having role=menuitemradio and coral-cyclebutton-actions having role=menuitem.
Coral.CycleButton is difficult to label for accessibility, because the only label is the current selection
https://jira.corp.adobe.com/browse/CUI-7343
Sub-tasks: 
1. [CUI-7340](https://jira.corp.adobe.com/browse/CUI-7340)  [Accessibility] Coral.Select should be tabbable …
=> CUI-7343 [Accessibility] Coral.CycleButton dropdown should behave as a single menu

coral-component-card/src/scripts/Card.js
Overflow class toggle to also check if alerts are present.
#28 
In AEM Editor, when using button inside a coral-card for Chrome and the card has a decimal height, the button becomes non-clickable when no alerts are present. The overflow class is added irrespective of whether alerts are present or not and depend solely on the height checks.
Tested in relation to https://jira.corp.adobe.com/browse/CQ-4274556
=> #28 Overflow class check only when there are alerts

coral-component-actionbar/src/scripts/ActionBar.js, coral-component-actionbar/src/scripts/ActionBarPrimary.js, coral-component-actionbar/src/scripts/ActionBarSecondary.js, coral-component-actionbar/src/scripts/BaseActionBarContainer.js, coral-component-actionbar/src/scripts/getFirstSelectableWrappedItem.js, coral-component-actionbar/src/tests/snippets/ActionBar.hiddenitems.html, coral-component-actionbar/src/tests/test.ActionBar.js
The changes fixes 2 issues :
1. ActionBar items which has selectable elements at 2nd level e.g. coral-fileupload are not selectable.
2. Offscreen ActionBar items are accessible.
1. Added code to find selectable elements in an ActionBar item if no selectable element found at first level.
2. Added code to set aria-hidden="true" to hide offscreen items from being read by screen-reader.
1. Manually tested with keyboard navigation.
=> CUI-7341 : Accessibility improvements for ActionBar

coral-component-select/src/scripts/SelectItem.js, coral-component-select/src/tests/test.Select.Item.js
On first render, if default select item value is an empty string, since it is falsy, it defaulted too eagerly to element's text (as if it was not present at all)
=> select to respect when select item value is an empty string

coral-component-list/src/scripts/SelectListItem.js
In IE11, when attempting to add a `coral-select-list-item` to a `coral-select-list`, if the `coral-select-list-item` is currently not within the DOM, then IE11 throws a SyntaxError on `content.querySelector('coral-icon:not(._coral-Menu-item-icon)')`. Specifically, it does not like the `:not` query selector for DOM-less elements, see https://github.com/FortAwesome/Font-Awesome/issues/12471.
This PR creates a polyfill for IE11, that ensures we can still remove the icons except `._coral-Menu-item-icon`s from the list item, without incurring a SyntaxError from IE11. This polyfill could have been extended to also check if the `content` is within the DOM, but I strongly suspect that tree-walking the DOM to find this element would be orders of magnitude slower than the array operations it does …
=> IE11 Polyfill for coral-select-list-item querySelector on DOM-less elements

coral-component-calendar/src/scripts/Calendar.js, coral-component-calendar/src/tests/test.Calendar.js
Datepicker component itself is made up of coral-calendar, coral popup component.  document.activeElement set to first tabbable element of popover which is "previous button" by popover component due to which "if " condition check failed and it never set focus to current date . I have changed document.activeElement by changing if condition.
In respect to accessibility , focus should be on current date on opening date picker.
=> [Accessibility]Focus should move to current date on Dialog/pop-up open

coral-component-table/examples/index.html, coral-component-table/src/scripts/Table.js, coral-component-table/src/tests/test.Table.js
Added support for aria-label and aria-labelledby for table using properties labelled and labelledby respectively
Missing aria-label and aria-labelledby support in table
I have run all test cases locally . Added new test cases to check new changes
=> Table: add aria-label and aria-labelledby

coral-component-table/src/scripts/Table.js, coral-component-table/src/tests/snippets/Table.sticky.sortable.html, coral-component-table/src/tests/test.Table.js
Added aria attributes to coral-table-headercell-content for sticky table 
Previously aria attributes were getting added to <th> tag which does not receive focus for sticky table. Hence, added aria attributes to coral-table-headercell-content which receives focus for sticky table  
Manually verified that all aria-sort is added/updated on  coral-table-headercell-content for sticky table.
I have run all test cases locally . Added new test cases to check new changes
=> Table: Add aria-attributes to coral-table-headercell-content for sticky table

coral-component-table/i18n/translations.js, coral-component-table/src/scripts/Table.js, coral-component-table/src/tests/test.Table.js
Added aria-live region in for announcing sortable column changes
Previously sorting order was not announced immediately after clicking the column. 
Manually verified updation of liveRegion upon changing the sorting order. 
I have run all test cases locally . Added new test cases to check new changes
=> Table: Add aria-live region in for announcing sortable column changes

coral-component-table/src/scripts/Table.js, coral-component-table/src/templates/base.html, coral-component-table/src/tests/test.Table.js
Per https://github.com/adobe/coral-spectrum/pull/39#discussion_r395187537
Live Region must have aria-live="polite" for 2500ms to give assistive technology time to pick up on update and announce the new sort order.
=> [Accessibility] Table: restore setTimeout to liveRegion announcement

coral-component-table/src/scripts/BaseTableSection.js, coral-component-table/src/tests/test.Table.Body.js, coral-component-table/src/tests/test.Table.Foot.js, coral-component-table/src/tests/test.Table.Head.js
role=rowgroup causes VoiceOver to announce table as "empty"
VoiceOver screen reader announces tables that use `role="rowgroup"` on `thead`, `tbody` or `tfoot` as empty, failing to communicate the number of rows or columns in the table.
=> [Accessibility] remove role="rowgroup" from BaseTableSection

coral-component-tablist/src/scripts/Tab.js, coral-component-tablist/src/styles/index.styl, coral-component-tablist/src/styles/light.styl, coral-component-tablist/src/styles/skin.styl, coral-component-tablist/src/tests/test.Tab.js
Adding an alert icon to invalid Coral Spectrum Tabs in order to improve accessibility.
When a Coral Spectrum Tab becomes invalid, it only uses the color red to signify that it's invalid. As Coral Spectrum may have users with impaired vision, there is need for a more robust approach. With this change, I'm adding a Coral Spectrum Icon that appears when the tab is invalid and hides when the tab becomes valid.
The icon is created during the Tab component render() method with the attribute `hidden` set. When the call to `setInvalid(value)` is made, the attribute is removed and the icon appears in the tab, depending on the value of `value`.
https://github.com/adobe/coral-spectrum/issues/48
This PR would improve Coral Spectrum accessibility by helping colour blind users to determine which tabs …
=> Adding alert icon to invalid Coral Spectrum Tabs

coral-component-columnview/src/scripts/ColumnViewColumn.js, coral-component-columnview/src/tests/test.ColumnView.js
The actual issue is that on selecting the item(clicking on thumbnail) in a column view(selectionMode : Single), it loads the next column.
The root cause is the code triggers the activate event of next column when an item is selected. AFAIU Setting an item as active results in loads item data , which is the folder content.
This is not the expected behaviour. In 6.3 , next column is not loaded on selecting asset thumbnail .
Have run Gulp build and verified everything run fines .
CQ Issue also got resolved after applying this fix.
=> CUI-7170 Coral.ColumnView: single selection loads next

examples/index.html
It's not perfect, but good enough!
This adds the navigation bar in the examples page so that users can navigate to 
Examples, Playground, Reference.. etc.
What would be perfect is to use proper HTML template files for all examples instead of repeating boilerplate HTML documents. Also, maybe build the whole thing into a shell page. Anyway, this works for now :)
=> Add Nav header to the Examples site. 

coral-component-select/examples/index.html, coral-component-select/src/scripts/Select.js, coral-component-select/src/templates/base.html, coral-component-select/src/tests/test.Select.js
When setting labelledBy or labelled attribute on Coral.Select, the value or placeholder displayed as the button label, as well as the invalid icon, should be included in the accessibility name for the control.
https://jira.corp.adobe.com/browse/CQ-4292656
Labelling a Coral.Select control, fails to include the selected value as part of the accessibility name.
Tested use VoiceOver on macOS and NVDA on Windows.
=> CQ-4292656 [Accessibility] Coral.Select include selected value and invalid icon in accessibility name

coral-component-list/src/scripts/SelectList.js, coral-component-list/src/tests/test.SelectList.js
Select list group component does not allow using keyboard to move between different groups and items below them. This PR adds tabindex on first element of each group. This will allow user to access each group using only keyboard.
=> [Accessibility] Making selectlist group items keyboard accessible

coral-component-table/src/tests/test.Table.js
CQ-4291310 introduced a unit test that fails intermittently. Lengthening the setTimeout delays in tests for "#a11y should add an accessibilityState and announce selection changes to selectable items" will hopefully make the tests more resilient.
Fixes: https://jira.corp.adobe.com/browse/CUI-7382,
which fixes: https://jira.corp.adobe.com/browse/CQ-4294893,
which was introduced by: https://jira.corp.adobe.com/browse/CQ-4291310.
Fix intermittent failing unit test.
=> CUI-7382 Coral.Table: fix unit test for accessibilityState

coral-component-colorinput/src/scripts/ColorInput.js, coral-component-colorinput/src/scripts/ColorInputSwatch.js, coral-component-colorinput/src/scripts/ColorInputSwatches.js, coral-component-colorinput/src/templates/base.html, coral-component-colorinput/src/templates/colorButton.html, coral-component-colorinput/src/templates/colorProperties.html, coral-component-colorinput/src/templates/swatchesHeader.html, coral-component-colorinput/src/tests/test.ColorInput.js, coral-component-slider/src/scripts/Slider.js
Refactor Coral.ColorInput to implement WAI-ARIA 1.2 Combobox design pattern where the `input` has `role="combobox"` rather than the container.
Note that this PR also includes several relevant fixes for labelling of color slider controls, and navigating the swatches listbox using the keyboard within the ColorInput dialog.
Per: https://jira.corp.adobe.com/browse/CQ-4292426
and https://jira.corp.adobe.com/browse/CUI-7373
Fixes an issue where NVDA get stuck in forms mode and the user is unable to navigate from the input to the dropdown button using the down arrow in browse mode.
Tested with VoiceOver on macOS and NVDA on Windows.
=> CUI-7373 [Accessibility] Coral.ColorInput: Use WAI-ARIA 1.2 Combobox design pattern

coral-component-calendar/src/scripts/Calendar.js, coral-component-calendar/src/templates/calendar.html, coral-component-datepicker/examples/index.html, coral-component-datepicker/src/scripts/Datepicker.js, coral-component-datepicker/src/templates/base.html, coral-component-datepicker/src/tests/test.Datepicker.js, coral-component-dialog/src/scripts/Dialog.js, coral-component-overlay/src/scripts/Overlay.js, coral-component-toast/src/scripts/Toast.js
Refactor Coral.Datepicker to implement WAI-ARIA 1.2 Combobox design pattern, where the `input` has `role="combobox"`, rather than the container element.
This PR also includes a fixes to Calendar for to the use case where no value is specified, so that the Calendar table grid is navigable using the keyboard.
Per https://jira.corp.adobe.com/browse/CQ-4292426
and https://jira.corp.adobe.com/browse/CUI-7371
Fixes an issue where NVDA get stuck in forms mode and the user is unable to navigate from the input to the dropdown button using the down arrow in browse mode.
Tested with VoiceOver on macOS and NVDA on Windows.
=> CUI-7371 [Accessibility] Coral.Datepicker: Use WAI-ARIA 1.2 Combobox design pattern

coral-component-autocomplete/examples/index.html, coral-component-autocomplete/src/scripts/Autocomplete.js, coral-component-autocomplete/src/templates/base.html, coral-component-autocomplete/src/tests/test.Autocomplete.js
Refactor Coral.Autocomplete to implement WAI-ARIA 1.2 Combobox design pattern where the `input` has `role="combobox"` rather than the container.
Per: https://jira.corp.adobe.com/browse/CQ-4292426
and https://jira.corp.adobe.com/browse/CUI-7370
Tested with VoiceOver on macOS and NVDA on Windows.
=> CUI-7370 [Accessibility] Coral.Autocomplete: Use WAI-ARIA 1.2 Combobox design pattern

coral-component-datepicker/src/scripts/Datepicker.js, coral-component-datepicker/src/tests/test.Datepicker.js, coral-component-select/src/scripts/Select.js, coral-component-select/src/tests/test.Select.js
For the bug CQ-4273031 we were needed to migrate attribute "disabled" to "readOnly" in supertype form fields (/libs/granite/ui/components/coral/foundation/form/field). This was done to make all the inheriting fields of form field accessible  based on following conditions:
1.            Able to make field displayable but not editable (read-only).
2.            User should be able to copy the text written underneath.
3.            User should be able to access the field with click(mouse) and tab(keyboard).
This was achieved by adding a new attribute "readOnly" in /libs/granite/ui/components/coral/foundation/form/field and leveraging it but apparently following components still didn't honour the attribute so to fix them we had to create the PRs [0] and [1]. And to honour them in …
=> Adseth CQ-4273031:Updating attributes in underlined elements in readOnly mode for select and datepicker.

coral-css-formgroup/examples/index.html, coral-css-formgroup/src/styles/dark.styl, coral-css-formgroup/src/styles/darkest.styl, coral-css-formgroup/src/styles/index.styl, coral-css-formgroup/src/styles/light.styl, coral-css-formgroup/src/styles/lightest.styl, coral-css-formgroup/src/styles/skin.styl, coral-theme-spectrum/src/styles/vars.css
Errors rely on color to communicate that they are errors.
Adding styles for a new coral-formfield-errorlabel that should
improve accesibility by adding a text that identifies the field
in error.
The text should have the color red and be situated below the input
field.
N/A
This PR would improve Coral Spectrum accessibility by helping colour blind users to determine what is the message for an invalid field.
The testing of the issue has been done using the examples page of the Coral Spectrum FormGroup component.
- [ X ] New feature (non-breaking change which adds functionality)
- [ X ] I have read the **CONTRIBUTING** document.
=> Errors rely on color to communicate that they are errors

coral-component-tablist/src/scripts/Tab.js, coral-component-tablist/src/styles/index.styl, coral-component-tablist/src/styles/light.styl, coral-component-tablist/src/styles/skin.styl, coral-component-tablist/src/tests/test.Tab.js, coral-theme-spectrum/src/styles/vars.css
Reapplying accessibility changes for Coral Tab invalid icon.
The changes were approved in #49, but were reverted shortly after due to test failures in Travis CI. I've added the changes back and checked that all tests are passing now. To not that Travis CI was failing due to Tooltip test failures:
https://travis-ci.com/github/adobe/coral-spectrum/builds/160158820
#48 
This PR would improve Coral Spectrum accessibility by helping colour blind users to determine which tabs are invalid or not.
The testing of the issue has been done using the examples page of the Coral Spectrum Tablist component. A unit test has been provided.
=> Adding back changes for Coral Tab invalid Icon

coral-component-autocomplete/src/tests/test.Autocomplete.js, coral-component-dialog/src/scripts/Dialog.js, coral-component-dialog/src/tests/test.Dialog.js
As per discussion in CQ-4292426 [0], coral-dialog component [1] needs support for aria-labelledBy and aria-describedBy properties, at least for the alertDialog so that the title of the dialog and description present in the body can be announced by screen readers.
[0] https://jira.corp.adobe.com/browse/CQ-4292426?focusedCommentId=21075521&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-21075521
[1] https://git.corp.adobe.com/Coral/coralui-component-dialog/blob/master/scripts/Coral.Dialog.js
https://jira.corp.adobe.com/browse/CUI-7368, https://jira.corp.adobe.com/browse/CQ-4292426
Improve screen reader announcement of `role=alertdialog` variants when the Cancel or Ok button receives focus.
=> CUI-7368 AlertDialog should have support for labelledBy and describedBy properties

coral-component-autocomplete/src/tests/test.Autocomplete.js, coral-component-panelstack/src/scripts/Panel.js, coral-component-panelstack/src/tests/test.Panel.js, coral-component-tablist/src/scripts/Tab.js, coral-component-tablist/src/scripts/TabList.js, coral-component-tablist/src/tests/test.TabList.js
CUI-7385 Coral.Panel should not have role="tabpanel" in use cases other than Tabs
By default Coral.Panel regions have role="tabpanel", which is inappropriate for use cases where a Panel is not used as part of Coral.TabView.
https://jira.corp.adobe.com/browse/CUI-7385
Migrating Coral.StepList away from an implementation that uses the Tabs WAI-ARIA design pattern revealed that Coral.PanelStack is used outside of TabView, where `role="tabpanel"` is  inappropriate.
=> CUI-7385 Coral.Panel should not have role="tabpanel" in use cases other than Tabs

coral-component-table/src/scripts/Table.js, coral-component-table/src/tests/test.Table.js
[Coral-Table]Provide a provision such that solutions can forced layout
Coral-Table: When large number of items are present inside table, then it takes time to load the items and call the debounced layout function. As a result, initially the client height of the table wrapper is wrong.Since there is no provision such that solutions can forced the layout. This is required because in Foundation when large items are loaded in table.
https://jira.corp.adobe.com/browse/CUI-7375
=> CUI-7375 : [Coral-Table]Provide a provision such that solutions can forced layout

coral-component-quickactions/examples/index.html, coral-component-quickactions/src/scripts/QuickActions.js, coral-component-quickactions/src/templates/base.html, coral-component-quickactions/src/tests/test.QuickActions.js
1. QuickActions should not trap focus on hover
2. When opened using a keyboard shortcut, Shift+F10 or Ctrl+Space, QuickAction should trap focus and navigate as a menu.
3. Provide an example of displaying QuickActions when an ancestor receives focus, as in AEM Masonry.
[CUI-7386](https://jira.corp.adobe.com/browse/CUI-7386),
[CQ-4293554](https://jira.corp.adobe.com/browse/CQ-4293554)
Coral.QuickActions in AEM currently steal focus by default when opened on hover, and focus is lost to the document.body when the QuickActions overlay is closed using the Esc key. This is extremely problematic for accessibility, because focus is stolen and never returned to where it was originally forcing a keyboard or screen reader user to navigate back through the web page to get back to the element with …
=> CUI-7386 Coral.QuickActions: dismissing items with Esc key should restore focus to last focused element

coral-component-masonry/examples/index.html, coral-component-masonry/src/scripts/Masonry.js, coral-component-masonry/src/tests/snippets/Masonry.ariagrid.html, coral-component-masonry/src/tests/test.Masonry.js
- Enables better accessibility support for Masonry component by adding WAI-ARIA grid roles, enabled setting a new attribute.
-  When enabled (`ariagrid="on"`), `role` and related attribute are added as follows:
-- Preserve current `role` attribute of the parent element of `<coral-masonry>` and set its new `role` as `grid`.
-- Preserve current `role` attribute of `<coral-masonry>`, and set new `role` as `row`.
-- Set `role` attribute of all child `<coral-masonry-item>` as `gridcell`.
-  When disabled (`ariagrid="off"`):
-- Restore preserved (if any) `role` attribute of the parent element of `<coral-masonry>`.
-- Restore preserved `role` attribute of the `<coral-masonry>`.
-- Remove `role` attribute of all child `<coral-masonry-item>`.
- Setting the attribute to other than allowed values …
=> CQ-4294648 [Masonry]: Added WAI-ARIA grid support for accessibility.

coral-component-steplist/examples/index.html, coral-component-steplist/i18n/translations.js, coral-component-steplist/src/scripts/Step.js, coral-component-steplist/src/scripts/StepList.js, coral-component-steplist/src/styles/dark.styl, coral-component-steplist/src/styles/darkest.styl, coral-component-steplist/src/styles/index.styl, coral-component-steplist/src/styles/light.styl, coral-component-steplist/src/styles/lightest.styl, coral-component-steplist/src/styles/skin.styl, coral-component-steplist/src/templates/step.html, coral-component-steplist/src/tests/test.Step.js, coral-component-steplist/src/tests/test.StepList.js
Included fixes
1. coral-steplist should have role="list"
2. Each coral-step should have role="listitem", with aria-setsize set to the total number of coral-step}}s in the {{coral-steplist, and aria-posinset set to the index position of each coral-step within the coral-steplist. These list items are not interactive and should not have a tabindex attribute.
3. Each coral-step should have as its child an a[href] or an element with [role="link"][tabindex="0"] that will receive focus and display the focused style.
4. The link for the current step should have the attribute aria-current="step", and should include a span with .u-coral-screenReaderOnly containing a localized string for "current: " as part of its label.
5. The links for completed steps should include a span with …
=> CQ-4373015 [coral-steplist] Inappropriate "tab", "tablist", "tabpanel" roles given to inactive progress indicators

coral-component-shell/src/styles/menubar/index.styl
In browse mode, NVDA reads elements with display: inline-block as a single block of text. For the Shell.MenuBar, where buttons are rendered with display: inline-block, all the buttons are announced as a line, rather than one button being announced with each ArrowDown. This is the expected behavior for NVDA, and the user can exit NVDA's screen layout mode using NVDA+V keyboard shortcut. However, it may create some confusion.
A workaround may be to use display: flex on ._coral-Shell-menubar, so that the items still appear inline, but do not use display: inline-block on ._coral-Shell-menubar-item.
https://jira.corp.adobe.com/browse/CUI-7391
[NVDA issue #11187 closed as not a bug](https://github.com/nvaccess/nvda/issues/11187)
Make navigation of MenuBar buttons in the Shell Header more …
=> CUI-7391 Coral.Shell.MenuBar: NVDA workaround screen layout announcement of buttons

coral-component-shell/examples/index.html, coral-component-shell/src/scripts/ShellMenuBar.js, coral-component-shell/src/scripts/ShellMenuBarItem.js, coral-component-shell/src/scripts/ShellUser.js, coral-component-shell/src/templates/menuBarItem.html, coral-component-shell/src/tests/test.Shell.MenuBar.Item.js, coral-component-shell/src/tests/test.Shell.MenuBar.js
In AEM, so that pressing Enter key with focus on a Search button within a Shell.MenuBar will open dialog and set focus to the Search box in forms mode, announcing the combobox with its accessibility name, the Shell.MenuBar.Item button button should have type="button".
We also need a way to set aria-haspopup and aria-expanded properties for buttons within Shell.MenuBar.Item.
https://jira.corp.adobe.com/browse/CUI-7390
https://jira.corp.adobe.com/browse/CQ-4293363
=> CUI-7390 Coral.Shell.MenuBar.Item button should have type="button"

coral-component-taglist/examples/index.html, coral-component-taglist/src/scripts/Tag.js, coral-component-taglist/src/scripts/TagList.js, coral-component-taglist/src/templates/base.html, coral-component-taglist/src/tests/test.TagList.js
Rather than a listbox, or list, Coral.TagList should implement the WAI-ARIA layout grid design pattern, similar to the authoring practices guide example: [Example 2: Pill List For a List of Message Recipients](https://www.w3.org/TR/wai-aria-practices-1.2/examples/grid/LayoutGrids.html#ex2_label).
https://jira.corp.adobe.com/browse/CQ-4294267
The original implementation in Coral used `role=listbox`, which made it difficult to express that a Tag, both exists and can be removed. For screen reader users, each element in the listbox, was an option with an aria-label to remove the item.
This was change to be presented as a static list, which wasn't a true representation of the behavior, because items can be navigated as a grid, using arrow keys and roving tabindex.
The layout grid design …
=> CQ-4294267 [CoralUI, Coral.TagList] Coral TagList to implement WAI-ARIA layout grid design pattern.

coral-component-columnview/src/scripts/ColumnView.js
If the text node of column view item contains a malicious script then on selecting the node results in execution of script.
We are passing the encoded values to coral, it seems that to support accessibility we are inserting to innerHTML which results in executing of scripts.
https://jira.corp.adobe.com/browse/CUI-7395
https://jira.corp.adobe.com/browse/CQ-4296454
https://jira.corp.adobe.com/browse/CQ-4297244
=> CUI-7395 : XSS in ColumnView item selection.

coral-component-shell/src/scripts/ShellHelp.js, coral-component-shell/src/templates/help.html, coral-component-shell/src/tests/test.Shell.Help.js
Use setTimeout so that screen readers have enough time to detect and announce the status changes.
https://jira.corp.adobe.com/browse/CUI-7393
https://jira.corp.adobe.com/browse/CQ-4293363
Ensures that status update messages are communicated to screen reader user when filtering help topics.
Tested using VoiceOver with Chrome and Safari on macOS.
Tested using NVDA with Chrome, Firefox and Edge on Windows 10
=> CUI-7393 Coral.ShellHelp: NVDA is not narrating ‘Searching help’ status message after searching any string in ‘Help Search’ field.

coral-component-columnview/src/scripts/ColumnViewItem.js, coral-component-columnview/src/tests/test.ColumnView.js
With VoiceOver for macOS, ColumnView item name is not announced when the item receives focus, and the aria-expanded state change announces instead. This has to do with setting active and expanding the element on focus.
Attempted fix is to add setTimeout to use aria-hidden to hide the control when aria-expanded state changes, and then to remove aria-hidden after a delay. This delays the announcement of aria-expanded state, giving focused element enough time to be announced.
https://jira.corp.adobe.com/browse/CQ-4272964
Fix announcement error that causes the user to lose context.
Tested with VoiceOver macOS using Chrome and Safari
=> CQ-4272964 Coral.ColumnView expanded/collapsed is announced as "row1 expanded" rather than cell name

coral-component-dialog/src/scripts/Dialog.js, coral-component-dialog/src/tests/test.Dialog.js
After Dialog opens and focuses an element other than the close button, include the close button in the tab order.
https://jira.corp.adobe.com/browse/CQ-4282133
https://jira.corp.adobe.com/browse/CUI-7392
For keyboard-only users, even though the Dialog can be closed using the Esc key, it is confusing for the Close button to not be included in the tab navigation order.
Tested using a keyboard in Coral-Spectrum example documentation.
=> CQ-42822133 Keyboard focus is not moving to the close(x) button present in 'Version Preview' dialog, while navigating using Keyboard TAB key.

coral-component-shell/src/scripts/ShellMenuBarItem.js
Shell.MenuBar.Item needs to support a hasPopup property so that if a menu has not been defined, aria-haspopup and aria-expanded can still be added to the shellMenuButton element, and aria-expanded can be controlled using the open prop.
https://jira.corp.adobe.com/browse/CUI-7396
https://jira.corp.adobe.com/browse/CQ-4293363
Addresses issue identified in Accessibility audit:
MSFT 4995958 - [Screen Readers-Adobe AEM- Home Page]:In Browse mode, NVDA is not narrating the state as ‘Expand/Collapse’ for ‘App’, ’Help’, ’Inbox’ and ‘User account’ buttons in header section.
Unit tests still pass.
Tested with http://localhost:9001/examples/#shell
=> CUI-7396 Coral.Shell.MenuBar.Item Add hasPopup prop

coral-component-columnview/src/scripts/ColumnViewItem.js, coral-component-columnview/src/tests/test.ColumnView.js
Per: https://jira.corp.adobe.com/browse/CQ-4272964?focusedCommentId=21693623&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21693623
> Following observations after latest fix
>
> Issue of "row 1 expanded" still persists. 
> Each cell expansion is announced as "Cell_name collapsed" rather tha "Cell_name expanded".
> For reproducing issue#1, 
> 1. Open asset properties page
> 2. Open tag picker
> 3. Enter columnview using keyboard controls
> 4. Use "up" and "down" keys to navigate between 4 options shown in first column. Let the voiceover complete its narration. Everytime it announces "row 1 collapsed row 1 expanded" after announcing correct names. Some times it directly announces "row 1 collapsed"
https://jira.corp.adobe.com/browse/CQ-4272964?focusedCommentI …
=> CQ-4272964 Refactor per JIRA comment 

coral-component-steplist/src/scripts/Step.js, coral-component-steplist/src/scripts/StepList.js, coral-component-steplist/src/tests/test.Step.js, coral-component-steplist/src/tests/test.StepList.js
In NVDA's browse mode, the label for each Step in the StepList must be accessible to screen readers when the StepList.size prop is "s" for small, or when the StepListItem.labelled prop is used to add an aria-label to the link.
1. Make sure that aria-label prop is rendered to the stepMarkerContainer when labelled prop has been assigned.
2. When StepList.size="s", ensure that the label element is visible to assistive technology by adding .u-coral-screenReaderOnly and display: block to the label element when the StepListItem does not use labelled.
[CUI-7399](https://jira.corp.adobe.com/browse/CUI-7399)
When StepList.size="s", the label is hidden using CSS with display: none, which makes the link inaccessible to screen reader users.
Updated unit tests.
Tested against example docs.
=> CUI-7399 StepList: fix labelled prop and size prop to better support NVDA browse mode

coral-component-table/src/scripts/TableRow.js, coral-component-table/src/tests/snippets/Table.selectable.html, coral-component-table/src/tests/test.Table.js
There is a need to add support for custom role attribute in table cell which could serve as rowheader.
Per: https://jira.corp.adobe.com/browse/CUI-7398 and
https://jira.corp.adobe.com/browse/CQ-4271825
Support `role="rowheader"` on table cells, and take row header in into account when calculating `aria-labelledby` which should help reduce the verbosity when focus is set to a table row.
Tested with VoiceOver in Google Chrome on macOS against examples page.
=> CUI-7398 Coral.Table: Add support for custom role attribute in table cell

coral-component-columnview/src/scripts/ColumnViewItem.js
Initially while updating the column view item the content zone can be out of DOM during initial upgrading phase. Aa a result this.content can be null, and attributeChangedCallback during upgradeElement in customElementInternal can result in NullPointer exception.
@review @icaraps @CezCz @majornista 
https://jira.corp.adobe.com/browse/CUI-7401
=> [ColumnView] - Rendering issue with content zone

coral-component-shell/src/scripts/ShellMenuBarItem.js
Per CQ-4293363#comment-21888821:
> 1. On pressing enter on any of the collapsed shell buttons like Solutions, Help, User, etc., NVDA briefly announces "expanded" but then it also announces "collapsed" again followed by "dialog" in some cases.
This seems to be caused in part by the rapid toggling of aria-expanded between coral-spectrum:beforeopen, coral-spectrum:open, and the setting of the open property, which was introduced with CUI-7390 and PR #88. We probably don't need to set aria-expanded on coral-spectrum:beforeopen, and should be careful to only update the attribute if its value is different from the current state of the overlay.
- [CUI-7405](https://jira.corp.adobe.com/browse/CUI-7405)
- [CQ-4293363#comment-21888821](https://jira.corp.adobe.com/browse/CQ-4293363?focusedCommentId=21 …
=> CUI-7405 Coral.Shell.MenuBar.Item fix aria-expanded when set in response to coral-overlay:open or coral-overlay:close event

coral-component-columnview/src/scripts/ColumnView.js, coral-component-columnview/src/scripts/ColumnViewColumn.js, coral-component-columnview/src/scripts/isInteractiveTarget.js, coral-component-columnview/src/styles/index.styl, coral-component-columnview/src/tests/snippets/ColumnView.coral-interactive.html, coral-component-columnview/src/tests/test.ColumnView.js
Like Accordion, some use cases of ColumnView require items to allow interactive descendants, like for example a checkbox.
To prevent keyboard and click events on the interactive descendants from bubbling up to be handled by the Item or ColumnView itself, we should support coral-interactive attribute to identify descendants that should be ignored.
Per https://jira.corp.adobe.com/browse/CUI-7402 and https://jira.corp.adobe.com/browse/CQ-4297530
Tested against Coral-Spectrum example by adding a checkbox with `[coral-interactive]` to several of the items.
=> CUI-7402 ColumnView should support coral-interactive on item descendants

coral-component-popover/src/scripts/Popover.js, coral-component-popover/src/tests/snippets/Popover.a11yOverrides.html, coral-component-popover/src/tests/test.Popover.js
For use cases where the Popover contains a listbox or menu, the Popover should support overriding the role attribute with role="presentation" and overriding the aria-live attribute with aria-live="off".
https://jira.corp.adobe.com/browse/CUI-7406
https://jira.corp.adobe.com/browse/CQ-4293363?focusedCommentId=22009932&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-22009932
For popovers Coral-Shell, we need to be able to set `aria-live="off"` so that opening popover doesn't announce too content.
Unit tests have been added and tested in Popover examples.
=> CUI-7406 Coral.Popover should support role and aria-live attribute override

coral-component-fileupload/src/scripts/FileUpload.js, coral-component-fileupload/src/tests/test.FileUpload.js
When the Coral.Fileupload button receives focus it moves focus immediately to a visually hidden file input element, yet when this input element receives focus, the .focus-ring style is lost on button.
[CUI-7409](https://jira.corp.adobe.com/browse/CUI-7409)
[CQ-4293594](https://jira.corp.adobe.com/browse/CQ-4293594)
Keyboard focus should be rendered when user closes Fileupload selection dialog using Esc key.
Tested using Example documentation
=> CUI-7409 Coral.Fileupload should support .focus-ring style when visually hidden file input has focus

coral-component-popover/examples/index.html, coral-component-popover/src/scripts/Popover.js, coral-component-popover/src/tests/test.Popover.js
Per CQ-4273029, when a Coral.Popover is associated with a target and that target has and aria-haspopup attribute, the aria-expanded prop should also be assigned to the target to communicate the open/closed state of the Popover.
- [CUI-7404](https://jira.corp.adobe.com/browse/CUI-7404)
- [CQ-4273029](https://jira.corp.adobe.com/browse/CQ-4273029)
Give users of assistive technology context for elements that open a popup.
Updated documentation example
=> CUI-7404 Coral.Popover should set aria-expanded on target with aria-haspopup attribute

coral-component-card/src/styles/index.styl
An issue was observed where the icon corresponding with coral-card-property shrinks in size as the associated content was increased. This was the case because of the CSS - `flex-shrink` wasn't set to 0.
https://jira.corp.adobe.com/browse/CUI-7411
https://jira.corp.adobe.com/browse/CQ-4300425
Solves the problem with the shrinking of an icon on long content in card-property.
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] I have read the **CONTRIBUTING** document.
=> Fixed the issue where the icon shrinks on inserting long content in coral-card-property

coral-component-accordion/examples/index.html, coral-component-accordion/src/scripts/Accordion.js, coral-component-accordion/src/scripts/AccordionItem.js, coral-component-accordion/src/tests/test.Accordion.js
So that nested Accordions can properly represent their heading level hierarchy, Coral-Spectrum should support the level prop to set the aria-level for each descendant h3 element.
[CUI-7408](https://jira.corp.adobe.com/browse/CUI-7408)
[CQ-4273103](https://jira.corp.adobe.com/browse/CQ-4273103?focusedCommentId=21990738&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21990738)
Accordions can be nested, so the heading levels for Accordion items should reflect the hierarchy.
Unit tests and Nested example has been updated to use `level="4"`, rather than the default `level="3"` on nested Accordion.
=> CUI-7408 [Accessibility] Coral-Spectrum Accordion should support level attribute

coral-component-actionbar/examples/index.html, coral-component-actionbar/src/scripts/ActionBar.js, coral-component-actionbar/src/scripts/BaseActionBarContainer.js, coral-component-actionbar/src/templates/moreOverlay.html, coral-component-actionbar/src/tests/test.ActionBar.js, coral-component-card/src/styles/index.styl, coral-component-fileupload/src/scripts/FileUpload.js, coral-component-tooltip/src/tests/test.Tooltip.js, coral-utils/src/tests/helpers/helpers.button.js
When a coral-fileupload is included within a coral-actionbar-item in coral-actionbar, when focus moves to the coral-fileupload, arrow key navigation within the coral-actionbar no longer works.
[CUI-7412](https://jira.corp.adobe.com/browse/CUI-7412)
[CUI-7409](https://jira.corp.adobe.com/browse/CUI-7409)
[CQ-4293594](https://jira.corp.adobe.com/browse/CQ-4293594)
Fixes navigation within ActionBar, and activation of FileUpload from "... More" menu.
Tested in Coral-Spectrum example for ActionBar
=> CUI-7412 Fix arrow key navigation when FileUpload is within ActionBar

coral-component-columnview/src/scripts/ColumnViewItem.js, coral-component-columnview/src/tests/test.ColumnView.js
Per: https://jira.corp.adobe.com/browse/CQ-4272964?focusedCommentId=21879694&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-21879694
> "row1 expanded", "row1 collapsed" is announced while navigating using up/down key in first column.
[CQ-4272964](https://jira.corp.adobe.com/browse/CQ-4272964)
Ensure that when a ColumnView item receives keyboard focus, it announces the element name rather than its expanded/collapsed state.
Tested in Coral-Spectrum example pages.
=> CQ-4272964 fix VoiceOver announcing elements as "row 1 expanded" on focus

coral-base-overlay/src/scripts/BaseOverlay.js, coral-base-overlay/src/tests/test.BaseOverlay.js, coral-component-actionbar/src/tests/test.ActionBar.js, coral-component-tooltip/examples/index.html, coral-component-tooltip/src/tests/test.Tooltip.js, coral-utils/src/tests/helpers/helpers.button.js
In Chrome, foundation-autocomplete in AEM is not including the error tooltip text as part of the accessibility name even though the appropriate IDREF is included in the aria-labelledby attribute for the combobox input.
Possible solution is to set visibility: initial on the coral-tooltip animation to close has completed. Chrome seems to ignore the element with display: none, visibility: hidden, and aria-hidden="true", when calculating the accessibility name.
[CUI-7416](https://jira.corp.adobe.com/browse/CUI-7416)
For accessibility, when a form element is invalid, we need to communicate the reason it is invalid to assistive technology.
Updated Tooltip example documentation to set aria-describedby on target element for tooltip. Accessibility description updates when the target tooltip …
=> CUI-7416 Coral-Spectrum Tooltip is not included in accessibility name when referenced using aria-labelledby

README.md
Updated README file to include information on how to render SVG icons internally (direct reference to attached shadow-root DOM SVG element/path) through Coral Spectrum, as opposed to externally (DOM references external SVG document and symbol by id to get path).
Several teams reporting issues rendering icons through Coral Spectrum.
Documentation does not mention additional steps to help resolve this issue.
Ran `gulp`, opened browser, verified changes.
n/a
=> :memo: chore(documentation): update README to provide information on turning external SVG rendering off

coral-base-formfield/src/scripts/BaseFormField.js, coral-base-formfield/src/tests/test.BaseFormField.js, coral-component-steplist/examples/index.html, coral-component-steplist/src/scripts/Step.js, coral-component-steplist/src/tests/test.Step.js
Step item should support describedBy attribute that maps to aria-describedby on the item link, and labelledBy attribute that maps to aria-labelledby on the step list marker image.
[CUI-7417](https://jira.corp.adobe.com/browse/CUI-7417)
For https://jira.corp.adobe.com/browse/CQ-4298385. Step item should support aria-describedby
Unit tests and example added to documentation
=> CUI-7417 [A11y] Coral.StepList should support labelledBy and describedBy on Step items

coral-base-overlay/src/scripts/BaseOverlay.js, coral-base-overlay/src/tests/test.BaseOverlay.js
In `connectedCallback`, if the overlay is closed, make sure that it is hidden with `display: none`, but set `visibility: visible` to ensure that the overlay will be included in accessibility name or description of an element that references it using `aria-labelledby` or `aria-describedby`.
[CUI-7416](https://jira.corp.adobe.com/browse/CUI-7416)
[CQ-4293363](https://jira.corp.adobe.com/browse/CQ-4293363)
Fix announcement of error instructions for invalid field when a closed tooltip is referenced with `aria-labelledby` or `aria-describedby`.
Tested with aria-describedby using Coral-Spectrun tooltip example.
=> CUI-7416 Coral-Spectrum Tooltip adjust visibility in connectedCallback

coral-component-columnview/src/scripts/ColumnViewItem.js, coral-component-columnview/src/tests/test.ColumnView.js
Since problem only seems to occur in first column of items within Chrome on MacOS, we omit aria-expanded on those items.
https://jira.corp.adobe.com/browse/CQ-4272964
Earlier attempts to correct the issue: 
https://github.com/adobe/coral-spectrum/pull/116
https://github.com/adobe/coral-spectrum/pull/91
https://github.com/adobe/coral-spectrum/pull/11
Earlier attempts failed to address the issue.
Tested against coral-spectrum examples and in context against a local CloudReady AEM instance.
=> CQ-4272964 ColumnView fix VoiceOver announcing elements as "row 1 expanded" on focus

coral-component-actionbar/src/scripts/BaseActionBarContainer.js
Per https://jira.corp.adobe.com/browse/CQ-4293592, closing the ActionBar submenu, that displays items that don't fit within the ActionBar, using the Escape key should restore focus to the More... button, ideally the event should not bubble to be handled by AEM's foundation-command.
[CUI-7420](https://jira.corp.adobe.com/browse/CUI-7420) and [CQ-4293592](https://jira.corp.adobe.com/browse/CQ-4293592)
Fix keyboard focus management in ActionBar for Collection views in AEM.
Tested in Coral-Spectrum examples and within CloudReady AEM instance.
=> CUI-7420 ActionBar: closing submenu using Escape should restore focus to the More... button

coral-component-actionbar/src/scripts/BaseActionBarContainer.js, coral-component-actionbar/src/tests/test.ActionBar.js
on clicking on action item inside a popover, another popover is displayed. "to.addEventListener('click', () => from.click());" hinders the click inside the popover to display another popover. 
@indra2gurjar Please review
@majornista  I am reverting the change in this file at line https://github.com/adobe/coral-spectrum/pull/132/files#diff-f6889f41ee5b8bc9ad89668528a7bc2aL42 made in this commit https://github.com/adobe/coral-spectrum/commit/be3d943b3c019e9709353acf588a98c710401574#diff-f6889f41ee5b8bc9ad89668528a7bc2a . as this is causing a regression that on clicking the relate button (when its inside the ... more popover), doesn't open the relation popover.
Also i have checked that after my change the https://jira.corp.adobe.com/browse/CQ-4293594 is working.  (arrow navigation to Add …
=> actions in more popover are not opening popover

coral-component-columnview/src/scripts/ColumnView.js, coral-component-columnview/src/scripts/ColumnViewItem.js, coral-component-columnview/src/tests/test.ColumnView.Item.js, coral-component-columnview/src/tests/test.ColumnView.js
Relating to https://jira.corp.adobe.com/browse/CQ-4301452, ColumnView items are being set to active twice. First with the focus event that comes on mouse down, and then again with the item click event on mouse up. This is causing choices to not be preserved in Granite's metadata schema editor, because when the item is already active, the item click event that follows does not trigger a `coral-columnview:activeitemchanged` event, which the schema editor uses to load the appropriate items and selection into the adjacent column: https://git.corp.adobe.com/Granite/com.adobe.granite.clientlibs.compiler/blob/master/src/test/resources/apps_libs5/libs/dam/gui/coral/components/admin/schemaforms/formbuilder/v2/clientlibs/js/cascadingschema/cascade.js#L176
https://jira.corp.adobe.com/browse/CUI-7422 …
=> CUI-7422 ColumnView item should not be set active twice when using the mouse

coral-component-columnview/src/scripts/ColumnView.js, coral-component-columnview/src/tests/test.ColumnView.js, package-lock.json, package.json
ColumnView sometimes fails to set a tabIndex="0" on first item when setting state from DOM. Fixes a race condition where ColumnView._ensureTabbableItem sets tabIndex before the ColumnViewItem renders, in which case, the first selectable item should already have a tabIndex attribute that should not be overwritten with -1 if the item is neither active nor selected.
https://jira.corp.adobe.com/browse/CUI-7426
https://jira.corp.adobe.com/browse/CQ-4293579
This PR ensures that the tabindex="0" is correctly set on first element while setting state from DOM. 
Unit tests have been added and the fixes have been tested against ColumnView examples.
=> fix(CUI-7426): ColumnView fails to call _ensureTabbableItem with _setStateFromDOM

coral-base-list/src/scripts/BaseList.js, coral-collection/src/scripts/SelectableCollection.js, coral-component-list/src/scripts/SelectList.js, coral-component-list/src/tests/test.SelectList.js, coral-component-select/src/scripts/Select.js
CQ-4295097 refactor _tabTarget setter and _resetTabTarget method
With SelectList groups only one item should receive focus at a time.
When resetting tabTarget, prioritized selected items over selectable items, but prioritize the last focused item over the first of the items in the array.
In Select component, we _resetTabTarget before the list opens, prioritizing the first selected item over the first selectable item.
#124 and https://jira.corp.adobe.com/browse/CQ-4295097
Correct behavior of a select list with option groups, by ensuring that only one item in the select list is tabbable at a time.
Behavior has been tested in example documents for SelectList and Select.
=> fix(CQ-4295097): Accessibility - Spectrum SelectList user is not able to select next group with keyboard

coral-base-overlay/src/scripts/BaseOverlay.js, coral-base-overlay/src/tests/test.BaseOverlay.js
Focus should be returned to right element before adding `display = none` otherwise focus will be lost to the `document.body`
https://jira.corp.adobe.com/browse/CUI-7430
https://jira.corp.adobe.com/browse/CQ-4293600
The PR ensures that focus should be returned to right element before adding `display = none` otherwise focus will be lost to the `document.body`
=> fix(CUI-7430): Coral.mixin.overlay should not hide overlay before calling _handleReturnFocus

coral-component-masonry/src/scripts/Masonry.js, coral-component-masonry/src/scripts/MasonryItem.js, coral-component-masonry/src/tests/snippets/Masonry.with.div.wrapper.html, coral-component-masonry/src/tests/test.Masonry.Item.js, coral-component-masonry/src/tests/test.Masonry.js
**Experienced Behaviour:** Whenever we tries to change the masonry parent element or reattach to same parent leads to the removal of its child items. 
**Expected Behaviour:** Changing the masonry parent should keep its child items intact.
**Changes:** If the item is connected to the DOM, don't run the disconnected callbacks. Test cases included.
Issue:  https://jira.corp.adobe.com/browse/CUI-7424
Steps to reproduce: Check [here](https://opensource.adobe.com/coral-spectrum/playground/#?livereload=true&screen=vertical&code=MTY1LDE0Niw0OSw3OSwxOTUsNDgsMTYsMTMzLDIzMSwyNDQsODcsMjQsNzksMjM3LDIwOCwxMjAsNywzOSwxOCw0Miw3Miw0OCwzMiwxNDQsOTYsOTcsMTE2LDIzNywxMDcsMjI3LDIxNCwxNzcsMTMxLDIzOSw4Miw0MSw2NiwyNTIsMTE5LDE0NiwxODQsMSwxODEsNjYsOTMsMTUyLDE4LDYxLDE5MSwyNTEsMjUyLDk0LDQ2LDI0MiwyMzQsMjM4LDEyMSwyNDUsM …
=> fix(Masonry): Changing Masonry parent leads to removal of its items

coral-component-calendar/src/styles/index.styl
See https://opensource.adobe.com/spectrum-css/calendar.html#focused
The grey background color for the .is-focused style on today's date is insufficient to communicate that the date has focus. We should use either the blue focus ring as we do for other focused styles, or to continue communicating that the date is today, some sort of double border.
https://jira.corp.adobe.com/browse/CUI-7432
https://jira.corp.adobe.com/browse/DNA-1057
https://jira.corp.adobe.com/browse/CQ-4293602
Tested against Coral-Spectrum example docs.
=> fix(CUI-7432) Calendar: is-focused style for today's date is insufficient to communicate the focused state

coral-component-columnview/src/scripts/ColumnViewColumn.js, coral-component-columnview/src/tests/test.ColumnView.js
Per CQ-4295167, the first Column of ColumnView should have role="presentation" so that items in the first column are at the root level of the tree.
Add unit test for the behavior in Coral-Spectrum.
- [CQ-4295167](https://jira.corp.adobe.com/browse/CQ-4295167)
- [CUI-7435](https://jira.corp.adobe.com/browse/CUI-7435)
Improve screen reader announcement with NVDA per [CQ-4295167](https://jira.corp.adobe.com/browse/CQ-4295167) :
> * Generally, role="group" should not be used as a container for the items in the root column of this tree, because the treeitem elements in the root column should be direct descendants of the tree. If the tree is properly labeled, this should simplify announcement of the items at the root level
Unit test has been added, and behavior has been verified in the rendered …
=> fix(CUI-7435) ColumnView: first column should have role="presentation"

coral-component-columnview/src/scripts/ColumnViewPreview.js, coral-component-columnview/src/tests/test.ColumnView.js
Per CQ-4295167, if a previous column has selected items, do not include ColumnView Preview item values in the tab order, so that a keyboard user can quickly advance to a subsequent toolbar without having to tab through the Preview item content.
- [CQ-4295167](https://jira.corp.adobe.com/browse/CQ-4295167)
- [CUI-7436](https://jira.corp.adobe.com/browse/CUI-7436)
So that a keyboard user can quickly advance to a subsequent toolbar without having to tab through the Preview item content when one or more items are selected.
Unit tests have been added, and tested against documentation examples
=> fix(CUI-7436) ColumnView.Preview should not be in tab order with selection in previous column

coral-base-component/src/scripts/BaseComponent.js, coral-component-accordion/src/scripts/AccordionItem.js, coral-component-autocomplete/src/scripts/AutocompleteItem.js, coral-component-cyclebutton/src/scripts/CycleButtonItem.js, coral-component-list/src/scripts/SelectListItem.js, coral-component-masonry/src/scripts/MasonryItem.js, coral-component-masonry/src/tests/test.Masonry.Item.js, coral-component-overlay/src/scripts/Overlay.js, coral-component-panelstack/src/scripts/Panel.js, coral-component-quickactions/src/scripts/QuickActionsItem.js, coral-component-select/src/scripts/SelectItem.js, coral-component-tablist/src/scripts/Tab.js, coral-component-tablist/src/scripts/TabList.js, coral-component-taglist/src/scripts/Tag.js
While trying to display a complex dialog, there is seen a performance drop. The scripting part of the dialog itself takes around 3000ms( ~3sec).
The related changes done in this PR :
a) Minimise the triggering of event, hence we are only changing the value and triggering event if the new value is different from old /previous stored value.
b) Sometimes callback running in animationFrame gets executed twice/thrice, even if executing them only once is sufficient. Hence avoid running them excessively.
Future Prospects :
a) Forced reflow occurring at some part of code. Try to find and reduce them.
b) If possible try to reduce the animationFrame callbacks . 
c) Reduce duplicated code to reduce downloading and scripting time.
The connectedCallback of the element can be executed more than once as …
=> fix(GRANITE-32187) : Massive performance drop in complex dialog openings with coral spectrum

coral-component-cyclebutton/src/scripts/CycleButton.js, coral-component-cyclebutton/src/templates/base.html, coral-component-cyclebutton/src/tests/test.CycleButton.js
Per https://jira.corp.adobe.com/browse/CUI-7441
In both the CoralUI and Coral Spectrum CycleButton implementations, the `menuitemradio` role on `coral-cyclebutton-item` and the `menuitem` role on `coral-cyclebutton-action` are not propagated to `coral-selectlist-item` and `button[is="coral-buttonlist-item"]` elements in the dropdown menu. Items within a menu should have a `menuitem*` role.
1. Open https://opensource.adobe.com/coral-spectrum/examples/#cyclebutton
2. Expand dropdown menu for the "With additional actions" CycleButton example.
3. Use the Web Inspector to inspect `coral-selectlist-item` elements in the `coral-selectlist[role="group"]` and `button[is="coral-buttonlist-item"]` in the `coral-buttonlist` contained within the `coral-popover[role="menu"]`.
coral-selectlist-item …
=> fix(CUI-7441): Coral.CycleButton: fix menuitemradio and menuitem roles

coral-component-select/src/styles/index.styl, coral-component-textfield/examples/index.html, coral-component-textfield/src/styles/index.styl
Placeholder text for Search, Select, Textarea and Textfield components should comply with [WCAG 2.1 AA contrast ratio requirements](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html) with a contrast ratio between the foreground text color and the background color or at least 4.5:1.
Currently, Coral-Spectrum uses `var(--spectrum-global-color-gray-600);`  from Spectrum-CSS, for the `::placeholder` text color in Search, Select, Textarea and Textfield components, which results in placeholder text with a contrast ratio of 3:1, which does not comply with [WCAG 2.1 AA contrast ratio requirements](https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html).
Spectrum-CSS includes a fix for this in v3.0.1, (see https://github.com/adobe/spectrum-css/commit/011ca5408ae5eb32bb55e …
=> fix(#165): placeholder text color contrast

coral-component-columnview/src/scripts/ColumnViewItem.js
On hovering over textcontent of columnview item html title will be visible
=> fix: adding html title feature in columnitem

coral-collection/src/scripts/Collection.js, coral-collection/src/tests/test.Collection.js, coral-component-accordion/src/scripts/Accordion.js, coral-component-buttongroup/src/scripts/ButtonGroup.js, coral-component-columnview/src/scripts/ColumnView.js, coral-component-columnview/src/scripts/ColumnViewColumn.js, coral-component-columnview/src/scripts/ColumnViewItem.js, coral-component-masonry/src/scripts/Masonry.js, coral-component-multifield/src/scripts/Multifield.js, coral-component-panelstack/src/scripts/PanelStack.js, coral-component-tree/src/scripts/TreeItem.js, coral-component-wizardview/src/scripts/WizardView.js
Change 1 : 
The mutation observer of collection observe all the changes happen in childlist as well as subtree. In some scenario, only listening to childlist is sufficient, for component whose items needs to be direct children.
https://github.com/adobe/coral-spectrum/pull/191/files#diff-3404a6f72ee6d617fc6a006eff08b6d76095d3206fcd4e3fc6b6644362070324R387 
Change 2 : 
The collection change triggers two event `coral-collection:add` when item is added and `coral-collection:remove` when item is removed. Sometimes we only require to know that collection is changed, adding `coral-collection:change` event to ensure that collection has been changed.
https://github.com/adobe/coral-spectrum/pull/191/files#diff-3404a6f72ee6d617fc6a006eff08b6d76095d3206fcd4e3fc6b6644362070324R353 
For component whose …
=> fix: performance improvement

coral-component-table/src/scripts/TableRow.js, coral-component-table/src/tests/test.Table.js
…how up on selection of assets
Sometimes,  when loading the table view with some around 100 items. The requestAnimationFrame gets executed before the [coral-table-roworder] item gets loaded in DOM. As a result, [coral-table-roworder] this attribute gets added to table item row (tr). 
This change syncs `coral-table-roworder` on setTimeout instead of requestAnimationFrame. 
When the tableview is loaded, sometimes intermittently actionBar does not gets loaded on selecting items. This happens b/c 
`coral-table-roworder` gets appended to table row even when there exists a [coral-table-roworder] element.
https://jira.corp.adobe.com/browse/GRANITE-37908
This has been tested visually and testcases are updated.
=> fix(GRANITE-37908): Intermittently action bar options don't show up on selection of items in tableview.

coral-component-tablist/src/scripts/Tab.js, coral-component-tablist/src/scripts/TabList.js, coral-component-tabview/src/scripts/TabView.js
…eing selected
When loading the properties page in aem, sometimes the coral-panelstack does not gets selected. This results in a blank page. This issue seems to be coral-panelstack getting constructed twice and the newer constructed panelstack replaces the old created panelstack but the tablist target has already been set to the older one.
The change is a workaround to sync the tablist target with new panelstack and update the selection.  
https://jira.corp.adobe.com/browse/CQ-4340781
=> fix(CQ-4340781): Blank screen for view Page Properties - Coral Tab not being selected

coral-component-dialog/src/scripts/Dialog.js
When loading the dialog sometimes, the content is not appended in the dialog wrapper and we try to insert the header wrapper before it, this result in javascript and lead to expected result.
This is a preventative check to add the headerWrapper if content is already appended or wait for a frame and then append headerWrapper.
https://jira.corp.adobe.com/browse/CUI-7460
CUI-7460 : [Hexaware] Facing issues while loading the Page in Production/Stage Author
Visually and running unit test cases to ensure no breaks.
=> CUI-7460: Intermittently rendering dialog resullt in error

coral-component-dialog/src/scripts/Dialog.js
When loading the dialog sometimes, the content is not appended in the dialog wrapper and we try to insert the header wrapper before it, this result in javascript and lead to expected result.
This is a preventative check to add the headerWrapper if content is already appended or wait for a frame and then append headerWrapper.
https://jira.corp.adobe.com/browse/CUI-7460
CUI-7460 : [Hexaware] Facing issues while loading the Page in Production/Stage Author
Visually and running unit test cases to ensure no breaks.
=> fix(CUI-7460): Intermittently rendering dialog resullt in error

coral-component-columnview/src/scripts/ColumnView.js
When using columnview components, it has been observed that intermittently it may not allow users to select a page. Specifically when loaded with horizontal scrollbar.
When columnview is loaded with horizontal scrollbar, if select an item the column is scrolled into view but scrollcallback was not getting called. This was because it was not passed when recursion scrollTo call was made.
=> fix(CQ-4341758): intermittently columnview does not allow selection

coral-component-table/src/scripts/Table.js, coral-component-table/src/tests/test.Table.js
Sometimes while loading the tableview, checkbox doesn't appear. This could be related to the fact that we disable the observer while loading the table template and as result the record might been dropping or the mutation might not be recorded as the observer is again set to on while body is appended. In some cases body mutation happens after the table has rendered as a result the already attached row are not correctly initialised.
When handling the mutation for body, we need take into account the addition of body element and the rows it currently contains. This way we can ensure the correct initialisation of all row element.
GRANITE-36119
Since this is a intermittent issue, we have tested it visually. The issue seems to be frequent in safari.
=> fix(GRANITE-36119): Asset selection checkbox doesn't appear for all the assets in list view

coral-component-actionbar/src/scripts/BaseActionBarContainer.js, coral-component-actionbar/src/templates/moreButton.html, coral-component-actionbar/src/tests/test.ActionBar.js
Asset information - Basic tab - '...' (more) button in the action bar does not have a programmatic text.
The screen reader should announce a programmatic label, such as "More".
@review @Pareesh 
Added aria label to '...' (more) button in the action bar.
https://jira.corp.adobe.com/browse/ASSETS-6913
The screen reader should announce a programmatic label for '...' (more) button in the action bar,  such as "More".
Checked if '...' (more) button has an aria-label attribute equal to "More".
=> fix(ASSETS-6913): Add aria-label to more button element

coral-component-dialog/src/scripts/Dialog.js
Added a aria-modal attribute on dialog.
The dialog is a modal window that prevents the user from navigating out of it. This type of dialog should be noted as such.
=> fix(CQ-4274470): Modal dialogs missing attributes

coral-component-accordion/src/scripts/AccordionItem.js
Hidden or empty element receive focus: removing focus from hidden radio buttons
Adding an if-statement in the accordion item component in order to check the state of the component and based on that, removing focus and hiding the content inside the accordion button. Improves user-experience for people using AT(ScreenReader, VoiceOver, etc.)
https://jira.corp.adobe.com/browse/SITES-2869
=> fix(SITES-2869): Hidden or empty element receive focus

coral-component-datepicker/src/scripts/Datepicker.js, coral-component-datepicker/src/tests/test.Datepicker.js
A keyboard user is unable to tab to the calendar button.
A keyboard user should be able to tab to the calendar button, and the element should be announced as a button.
@review @Pareesh @RitwikSrivastava
Set the tabindex attribute of calendar button according to the disabled attribute value.
https://jira.corp.adobe.com/browse/ASSETS-6857
A keyboard user should be able to tab to the calendar button, and the element should be announced as a button.
By tabbing through the asset manage publication page and by checking if tabindex attribute of calendar button is "-1" when disabled and "0" when is not disabled.
=> fix(ASSETS-6857): Set the tabindex attribute of calendar button according to the disabled attribute value

coral-component-clock/i18n/translations.js, coral-component-clock/src/scripts/Clock.js, coral-component-clock/src/templates/base.html, coral-component-clock/src/tests/test.Clock.js
https://jira.corp.adobe.com/browse/ASSETS-6921
https://jira.corp.adobe.com/browse/ASSETS-6920
https://jira.corp.adobe.com/browse/ASSETS-6852
Added an error label to coral clock that is displayed whenever the hours and/or minutes inputs are invalid.
Tested manually  & with screen reader
=> fix(ASSETS-6921): Hours and Minutes validation error label not available

coral-component-multifield/src/scripts/Multifield.js, coral-component-multifield/src/tests/test.Multifield.js
When the "Keywords" region does not contain any input fields, consider removing the role="list" attribute from the element.
As the "Add" button is pressed and the input fields (which contain the expected role="listitem") appear, consider using JavaScript to add role="list" back to the element.
@review @Pareesh @RitwikSrivastava 
Handle role list attribute according to the number of items.
When coral-multifield list of items is empty, the role should change.
https://jira.corp.adobe.com/browse/ASSETS-6863
Only when the list of items is not empty should have the role list attribute added.
By adding and removing items.
=> fix(ASSETS-6863): Files: Asset information - IPTC tab - Certain ARIA roles must contain particular children

coral-component-taglist/src/scripts/TagList.js, coral-component-taglist/src/tests/test.TagList.js
- adding `role=grid` attribute to `coral-taglist` elements when they have a child with `role=row` attribute 
- removing the `role=grid` attribute from `coral-taglist` when it has no child
https://jira.corp.adobe.com/browse/ASSETS-6862
https://jira.corp.adobe.com/browse/ASSETS-6858
Solves accessibility issue that affects user population: Without Vision, With Limited Vision, With Limited Manipulation, With Limited Reach and Strength, With Limited Language, Cognitive, and Learning Abilities
- tested manually by adding/removing `coral-tag` elements on `coral-taglist` items and observing that the `role` attributes are added/removed accordingly
=> fix(ASSETS-6862): Files: Filter - Required ARIA child role is missing

coral-component-masonry/examples/index.html, coral-component-masonry/src/scripts/Masonry.js, coral-component-masonry/src/scripts/MasonryItem.js, coral-component-masonry/src/tests/test.Masonry.js, coral-gulp/configs/karma.conf.js
1. Incorporate #245 to ensure that the `coral-masonry` grid is identified as supporting selection using `aria-multiselectable`.
2. Hide the `coral-checkbox` component using `aria-hidden="true"`, so that while it provides a visual affordance for the selected state, the selected state for the item will be communicated to assistive technology using `aria-selected` on each of the cells.
3. Ensure that `aria-selected` attribute is included on each masonry item, when `selectionMode !== 'none'`.
4. Ensure that the `accessibilityState` status message is not hidden on mac-like devices when the item is selected. This should ensure that the "Checked" state of an item is communicated by VoiceOver.
#249 and ASSETS-6844
Described in ASSETS-6844
=> fix(#249): [Masonry][Accessibility] Files: Main Navigation (Card View) - Selected state of the folder is not announced to the screen reader

coral-component-autocomplete/src/scripts/Autocomplete.js
preference would be first given to innerText instead of innerHtml in case of reflectCurrentValues as special characters like '&' transformed as ;amp in case of innerHtml
=> fix(Granite 37225): Autocomplete items containing HTML character references don't render when selected with arrow keys

coral-component-multifield/src/scripts/Multifield.js
This PR is adding aria-label="Add a new item to the options list" on multifield add button as was requested by the CQ-4273759 ticket. This adds necessary context for screen reader users. @Pareesh
=> fix(CQ-4273759): Added aria-label to multifield add new item button

coral-component-shell/src/styles/menubar/index.styl
Adjusted background colour of the notification icon so that it has the 4.5:1 ratio now with the white text
Adjusted background colour of the notification icon so that it has the 4.5:1 ratio now with the white text
https://jira.corp.adobe.com/browse/ASSETS-17347
Tested in my local AEM 6.6 instance
- [ x] Bug fix (non-breaking change which fixes an issue)
=> fix(ASSETS-17347) - Text content lacks 4.5:1 contrast ratio.

coral-component-shell/src/templates/user.html, coral-component-shell/src/tests/test.Shell.User.js
added "alt" attribute on user icon
https://jira.corp.adobe.com/browse/ASSETS-17263
=> fix(ASSETS-17263) - The decorative image is not hidden from screen readers

coral-component-calendar/src/styles/index.styl
https://jira.corp.adobe.com/browse/ASSETS-17241
In AEM 6.6 calendar, the background color of selected date does not have enough contrast against the white calendar background.
Added darker blue background color and white text color to selected date and increased ration to 5:1
=> fix(ASSETS-17241): Focus indicator is missing.

coral-component-colorpicker/src/scripts/ColorPicker.js, coral-component-colorpicker/src/scripts/ColorProperties.js, coral-component-colorpicker/src/tests/test.ColorProperties.js
1. color text change after input due to conversion - it seem to happen due to change event [triggered](https://github.com/adobe/coral-spectrum/blob/master/coral-component-colorpicker/src/scripts/ColorProperties.js#L210) after text change. colors in coral-picker lib are stored in hsl format as color-area support hsl only & then converted back to selected format which result in text change due to rounding double values. possible solution is to not update text-field if event is triggered from text-field.
2. color area should update as input text change - currently there is only [event](https://github.com/adobe/coral-spectrum/blob/master/coral-component-colorpicker/src/scripts/ColorProperties.js#L38) for change on text-field which trigger on focus close. possible solution is add …
=> fix(ASSETS-22047): Color picker improvement

coral-component-list/src/styles/index.styl
https://jira.corp.adobe.com/browse/ASSETS-25759
Added border around `_coral-Menu-item`s when in focus to fix visibility when used in Windows high contrast mode
Screenshots:
=> fix(Accessibility): Focus is not visible on dropdown elements in high contrast

coral-component-tooltip/src/scripts/Tooltip.js
As per MDN docs : `Tooltip must stay open when the mouse moves over the tooltip itself, and should also close when the user presses the Escape key.`
The above statement is implemented. 
Added code to cancel hide when mouse enter tooltip and hide when mouse leave tooltip only when target is not focused.
=> fix: Tooltip should be visible when mouse hover over tooltip

coral-component-datepicker/src/scripts/Datepicker.js
With required attribute, at first :invalid selector of coral-textfield triggered and showed input as red.
using aria-required attribute instead of required.
=> fix: Datepicker required functionality is incorrect.

coral-theme-spectrum/src/styles/vars.css
https://jira.corp.adobe.com/browse/SITES-10906
In this PR I added a new variable that contains the right color for the background so that the issue mentioned in the ticket will not be reproduced.
In the PR mentioned below you can see the difference in the images:
https://git.corp.adobe.com/Granite/com.adobe.granite.ui.coral-spectrum/pull/167
=> fix: Add coral tabs item background color

coral-component-actionbar/src/scripts/BaseActionBarContainer.js
Add Rendition Button was not working when resolution is more then 1440px width when only "Add Rendition" option is in the dropdown option.
=> fix: ActionBar overlay button does not work when has one child

coral-theme-spectrum/src/styles/vars.css
Ticket: [SITES-10905](https://jira.corp.adobe.com/browse/SITES-10905)
Added variables for the global bar that are used in this PR: https://git.corp.adobe.com/Granite/com.adobe.granite.ui.coral-spectrum/pull/174
=> fix(SITES-10905) State of active component lacks 3 to 1 contrast ratio.

coral-component-table/src/scripts/Table.js, coral-component-table/src/tests/test.Table.js
Ticket: [SITES-10962](https://jira.corp.adobe.com/browse/SITES-10962)
=> fix(Accessability): Add button role to table header interactive element

coral-component-dialog/src/tests/test.Dialog.js, coral-component-table/examples/index.html, coral-component-table/i18n/translations.js, coral-component-table/src/scripts/Table.js, coral-component-table/src/scripts/TableRow.js, coral-component-table/src/tests/test.Table.js, coral-dragaction/src/scripts/DragAction.js, coral-dragaction/src/tests/test.DragAction.js, coral-gulp/configs/karma.conf.js, coral-utils/src/scripts/Commons.js, coral-utils/src/scripts/Events.js
JIRA Ticket: https://jira.corp.adobe.com/browse/SITES-2864
=> fix(Accessibility): Drag and Drop feature is not keyboard accessible

coral-component-shell/src/styles/header/index.styl
Ticket: [SITES-26913](https://jira.corp.adobe.com/browse/SITES-26913)
=> fix (SITES-26913): Microsoft AEMaaCS Accessibility Bug - While using Keyboard, "Adobe experience manager" link focus is not clearly visible

coral-component-toast/src/scripts/Toast.js, coral-component-toast/src/tests/test.Toast.js
ticket: [SITES-27143](https://jira.corp.adobe.com/browse/SITES-27143)
Changing the role to alert to make sure that screen reader announce it once it is displayed, with status it might get undetected.
=> fix(Accessibility) : Info alert not getting announced

coral-component-dialog/examples/index.html, coral-component-dialog/src/scripts/Dialog.js, package-lock.json
- Ensure that headings are not nested
- Verify that header does not contain interactive elements before adding role="heading" and aria-level="2"
- Provide example for properly labelling the dialog and providing a header when the header element contains interactive controls.
SITES-27152
=> fix(accessibility): Remove heading role that contains interactive elements

coral-component-multifield/src/scripts/Multifield.js, coral-component-multifield/src/scripts/MultifieldItem.js, coral-dragaction/src/scripts/DragAction.js
=> fix: multifield item not scrollable when dragged
